export const GET_USER_MANAGERMENT_SYSTEM = 'user_managerment/GET_USER_MANAGERMENT_SYSTEM';
export const GET_USER_MANAGERMENT_SYSTEM_DETAIL = 'user_managerment/GET_USER_MANAGERMENT_SYSTEM_DETAIL';
export const CREATE_USER_MANAGERMENT_SYSTEM = 'user_managerment/CREATE_USER_MANAGERMENT_SYSTEM';
export const UPDATE_USER_MANAGERMENT_SYSTEM = 'user_managerment/UPDATE_USER_MANAGERMENT_SYSTEM';
export const DELETE_USER_MANAGERMENT_SYSTEM = 'user_managerment/DELETE_USER_MANAGERMENT_SYSTEM';
