export const GET_PRODUCT_SPECIFICATION = 'items/GET_PRODUCT_SPECIFICATION';
export const GET_PRODUCT_SPECIFICATION_DETAIL = 'items/GET_PRODUCT_SPECIFICATION_DETAIL'
export const CREATE_PRODUCT_SPECIFICATION = 'items/CREATE_PRODUCT_SPECIFICATION'
export const UPLOAD_PRODUCT_SPECIFICATION = 'items/UPLOAD_PRODUCT_SPECIFICATION'
export const DELETE_PRODUCT_SPECIFICATION = 'items/DELETE_PRODUCT_SPECIFICATION'