export const GET_PRICING_PRODUCTS = 'pricingSystem/GET_PRICING_PRODUCTS';
export const GET_PRICING_PRODUCT_STATISTIC = 'pricingSystem/GET_PRICING_PRODUCT_STATISTIC';
export const GET_PRICING_PRODUCT_DETAIL = 'pricingSystem/GET_PRICING_PRODUCT_DETAIL';
export const CREATE_PRICING_PRODUCT = 'pricingSystem/CREATE_PRICING_PRODUCT';
export const UPLOAD_PRICING_PRODUCT = 'pricingSystem/UPLOAD_PRICING_PRODUCT';
export const DELETE_PRICING_PRODUCT = 'pricingSystem/DELETE_PRICING_PRODUCT';
export const ACTIVATE_PRICING_PRODUCT = 'pricingSystem/ACTIVATE_PRICING_PRODUCT';
export const DEACTIVATE_PRICING_PRODUCT = 'pricingSystem/DEACTIVATE_PRICING_PRODUCT';
