export const GET_SPECIFICATION = 'items/GET_SPECIFICATION';
export const GET_SPECIFICATION_DETAIL = 'items/GET_SPECIFICATION_DETAIL'
export const CREATE_SPECIFICATION = 'items/CREATE_SPECIFICATION'
export const UPLOAD_SPECIFICATION = 'items/UPLOAD_SPECIFICATION'
export const DELETE_SPECIFICATION = 'items/DELETE_SPECIFICATION'