export const GET_COMPANY_PROFILE_DETAIL = 'companyProfile/GET_COMPANY_PROFILE_DETAIL';
export const CREATE_COMPANY_PROFILE = 'companyProfile/CREATE_COMPANY_PROFILE';
export const UPDATE_COMPANY_PROFILE = 'companyProfile/UPDATE_COMPANY_PROFILE';
