export const GET_PAYMENT = 'payment/GET_PAYMENT';
export const GET_PAYMENT_DETAIL = 'payment/GET_PAYMENT_DETAIL';
export const CREATE_PAYMENT = 'payment/CREATE_PAYMENT';
export const UPLOAD_PAYMENT = 'payment/UPLOAD_PAYMENT';
export const DELETE_PAYMENT = 'payment/DELETE_PAYMENT';

export const GET_PAYMENT_DASHBOARD = 'payment/GET_PAYMENT_DASHBOARD';
export const GET_PAYMENT_MEMBERS = 'payment/GET_PAYMENT_MEMBERS';
export const GET_PAYMENT_STATISTIC = 'payment/GET_PAYMENT_STATISTIC';
export const APPROVE_BANK_ORDER_PAYMENT = 'payment/APPROVE_BANK_ORDER_PAYMENT';
export const APPROVE_BANK_REPAIR_PAYMENT = 'payment/APPROVE_BANK_REPAIR_PAYMENT';
export const REJECT_BANK_REPAIR_PAYMENT = 'payment/REJECT_BANK_REPAIR_PAYMENT';
