export const GET_AR_INVOICE = 'arInvoice/GET_AR_INVOICE';
export const GET_CREATE_AR_INVOICE = 'arInvoice/GET_CREATE_AR_INVOICE';
export const GET_CREATE_AR_INVOICE_DETAIL = 'arInvoice/GET_CREATE_AR_INVOICE_DETAIL';
export const GET_DELIVERY_ORDER = 'arInvoice/GET_DELIVERY_ORDER';
