export const GET_INSURANCE_PROMOTIONS = 'promotion/GET_INSURANCE_PROMOTIONS';

export const GET_INSURANCE_PROMOTION_DETAIL = 'promotion/GET_INSURANCE_PROMOTION_DETAIL';

export const CREATE_INSURANCE_DISCOUNT = 'promotion/CREATE_INSURANCE_DISCOUNT';
export const CREATE_INSURANCE_COUPON = 'promotion/CREATE_INSURANCE_COUPON';

export const UPDATE_INSURANCE_PROMOTION = 'promotion/UPDATE_INSURANCE_PROMOTION';

export const DELETE_INSURANCE_PROMOTION = 'promotion/DELETE_INSURANCE_PROMOTION';
