export const GET_INSURANCE_ORDER = 'package/GET_INSURANCE_ORDER';
export const GET_INSURANCE_ORDER_STATISTIC = 'package/GET_INSURANCE_ORDER_STATISTIC';
export const GET_INSURANCE_ORDER_DETAIL = 'package/GET_INSURANCE_ORDER_DETAIL';
export const CREATE_INSURANCE_ORDER = 'package/CREATE_INSURANCE_ORDER';
export const UPDATE_INSURANCE_ORDER = 'package/UPDATE_INSURANCE_ORDER';
export const DELETE_INSURANCE_ORDER = 'package/DELETE_INSURANCE_ORDER';
export const APPROVE_INSURANCE_ORDER = 'package/APPROVE_INSURANCE_ORDER';
export const REJECT_INSURANCE_ORDER = 'package/REJECT_INSURANCE_ORDER';
