export const GET_CURRENT_SETTINGS = 'settings/GET_CURRENT_SETTINGS';
export const UPDATE_SETTINGS = 'settings/UPDATE_SETTINGS';

// category
export const GET_SETTINGS_CATEGORY = 'settings/GET_SETTINGS_CATEGORY';
export const GET_VENDOR_SUPPORTED_CATEGORY = 'settings/GET_VENDOR_SUPPORTED_CATEGORY';
export const UPDATE_SETTINGS_CATEGORY = 'settings/UPDATE_SETTINGS_CATEGORY';

// service
export const GET_CATEGORY_SUPPORTED_SERVICE = 'settings/GET_CATEGORY_SUPPORTED_SERVICE';
export const UPDATE_SETTINGS_SERVICE = 'settings/UPDATE_SETTINGS_SERVICE';

// vehicle
export const GET_SETTINGS_VEHICLE = 'settings/GET_SETTINGS_VEHICLE';
export const GET_VENDOR_SUPPORTED_VEHICLE = 'settings/GET_VENDOR_SUPPORTED_VEHICLE';
export const UPDATE_SETTINGS_VEHICLE = 'settings/UPDATE_SETTINGS_VEHICLE';
