//GET LIST AND DETAIL PROMOTION
export const GET_PROMOTIONS = 'promotion/GET_PROMOTION';
export const GET_PROMOTION_DETAIL = 'promotion/GET_PROMOTION_DETAIL';
export const GET_COUPONS = 'promotion/GET_COUPONS';
export const GET_COUPON_DETAIL = 'promotion/GET_COUPON_DETAIL';
export const UPDATE_PROMOTION = 'promotion/UPDATE_PROMOTION';
export const DELETE_PROMOTION = 'promotion/DELETE_PROMOTION';
//GET LIST AND DETAIL PROMOTION

//INVOICE_DISCOUNT
export const CREATE_INVOICE_DISCOUNT = 'promotion/CREATE_INVOICE_DISCOUNT';
export const UPDATE_INVOICE_DISCOUNT = 'promotion/UPDATE_INVOICE_DISCOUNT';
//INVOICE_DISCOUNT

//CATEGORIES_PROMOTION
export const CREATE_CATEGORIES_PROMOTION = 'promotion/CREATE_CATEGORIES_PROMOTION';
export const UPDATE_CATEGORIES_PROMOTION = 'promotion/UPDATE_CATEGORIES_PROMOTION';
//CATEGORIES_PROMOTION

//TRADING_PRODUCT_PROMOTION
export const CREATE_TRADING_PRODUCT_PROMOTION = 'promotion/CREATE_TRADING_PRODUCT_PROMOTION';
export const UPDATE_TRADING_PRODUCT_PROMOTION = 'promotion/UPDATE_TRADING_PRODUCT_PROMOTION';
//TRADING_PRODUCT_PROMOTION

//COUPON
export const CREATE_COUPON = 'promotion/CREATE_COUPON';
export const UPDATE_COUPON = 'promotion/UPDATE_COUPON';
//COUPON
