export const GET_SERVICE_PROMOTION = 'video/GET_SERVICE_PROMOTION';
export const GET_SERVICE_PROMOTION_DETAIL = 'video/GET_SERVICE_PROMOTION_DETAIL';
export const CREATE_SERVICE_PROMOTION = 'video/CREATE_SERVICE_PROMOTION';
export const CREATE_SERVICE_PROMOTION_NEW = 'video/CREATE_SERVICE_PROMOTION_NEW';
export const UPDATE_SERVICE_PROMOTION = 'video/UPDATE_SERVICE_PROMOTION';
export const APPLY_SERVICE_PROMOTION = 'video/APPLY_SERVICE_PROMOTION';

export const DELETE_SERVICE_PROMOTION = 'video/DELETE_SERVICE_PROMOTION';
